### ISSUE TITLE
this is so cool

### ISSUE THREAD

**Issue by stretch07** [themirrazz/IoT96#1]
how to use ? 2022 version working

g

**Comment by themirrazz** [comment]
Step 1. Visit https://iot96.repl.co/
Step 2. Download the installer and follow the instructions for the version of Windows 96 you’re using
Step 3. Visit https://dash.iot96.repl.co/ and create an account
Step 4. Visit ifttt.com
Step 5. Create a new applet and look for the service called “IoT96”
Step 6. Connect to your IoT96 account and enjoy 😉

Note: since this isn’t approved yet, you’ll have to have the testing link to try it out
